-- Phase 39-02: Key votes table + councillor_highlights narrative column
-- Stores pre-computed notable votes (minority position, close votes, ally breaks)

-- ── Key Votes Table ─────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS key_votes (
  id bigint generated by default as identity primary key,
  person_id bigint REFERENCES people(id) ON DELETE CASCADE NOT NULL,
  motion_id bigint REFERENCES motions(id) ON DELETE CASCADE NOT NULL,
  vote text NOT NULL,
  detection_type text[] NOT NULL,
  composite_score float NOT NULL,
  context_summary text,
  ally_breaks jsonb,
  vote_split text,
  generated_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  UNIQUE(person_id, motion_id)
);

-- RLS: public read access
ALTER TABLE key_votes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read access for key_votes"
  ON key_votes FOR SELECT
  USING (true);

-- Timestamp trigger (reuse existing function from bootstrap.sql)
CREATE TRIGGER update_key_votes_updated_at
  BEFORE UPDATE ON key_votes
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_key_votes_person_id ON key_votes(person_id);
CREATE INDEX IF NOT EXISTS idx_key_votes_composite_score ON key_votes(composite_score DESC);

-- ── Councillor Highlights: Add narrative columns ────────────────────────

ALTER TABLE councillor_highlights
  ADD COLUMN IF NOT EXISTS narrative text;

ALTER TABLE councillor_highlights
  ADD COLUMN IF NOT EXISTS narrative_generated_at timestamptz;
