-- Migration: add_extracted_documents_and_images
-- Phase: 07.1-upgrade-document-extraction, Plan 01
-- Creates extracted_documents and document_images tables,
-- adds extracted_document_id FK to document_sections

-- ══════════════════════════════════════════════════════════════
-- 1. extracted_documents — intermediate layer between documents
--    (source PDF files) and document_sections
-- ══════════════════════════════════════════════════════════════

CREATE TABLE extracted_documents (
    id bigint generated by default as identity primary key,
    document_id bigint REFERENCES documents(id) ON DELETE CASCADE NOT NULL,
    agenda_item_id bigint REFERENCES agenda_items(id) ON DELETE SET NULL,
    title text NOT NULL,
    document_type text NOT NULL DEFAULT 'other',
    page_start integer,
    page_end integer,
    summary text,
    key_facts jsonb,
    municipality_id bigint REFERENCES municipalities(id) DEFAULT 1,
    created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- document_type values: agenda, minutes, staff_report, delegation,
-- correspondence, appendix, bylaw, presentation, form, other

CREATE INDEX idx_extracted_documents_document ON extracted_documents(document_id);
CREATE INDEX idx_extracted_documents_agenda_item ON extracted_documents(agenda_item_id);
CREATE INDEX idx_extracted_documents_type ON extracted_documents(document_type);

ALTER TABLE extracted_documents ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON extracted_documents FOR SELECT USING (true);

-- ══════════════════════════════════════════════════════════════
-- 2. document_images — R2 image metadata
-- ══════════════════════════════════════════════════════════════

CREATE TABLE document_images (
    id bigint generated by default as identity primary key,
    extracted_document_id bigint REFERENCES extracted_documents(id) ON DELETE CASCADE NOT NULL,
    r2_key text NOT NULL,
    page integer NOT NULL,
    description text,
    image_type text DEFAULT 'other',
    width integer,
    height integer,
    format text,
    file_size integer,
    municipality_id bigint REFERENCES municipalities(id) DEFAULT 1,
    created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- image_type values: map, site_plan, chart, diagram, rendering, photo, other

CREATE INDEX idx_document_images_extracted_doc ON document_images(extracted_document_id);

ALTER TABLE document_images ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON document_images FOR SELECT USING (true);

-- ══════════════════════════════════════════════════════════════
-- 3. Add extracted_document_id FK to document_sections
-- ══════════════════════════════════════════════════════════════

ALTER TABLE document_sections
    ADD COLUMN extracted_document_id bigint REFERENCES extracted_documents(id) ON DELETE CASCADE;

CREATE INDEX idx_document_sections_extracted_doc ON document_sections(extracted_document_id);
