-- Migration: create_document_sections
-- Phase: 07-document-intelligence, Plan 01
-- Creates document_sections table for granular PDF section storage with
-- vector embeddings and full-text search

-- Table
CREATE TABLE document_sections (
    id bigint generated by default as identity primary key,
    document_id bigint REFERENCES documents(id) ON DELETE CASCADE NOT NULL,
    agenda_item_id bigint REFERENCES agenda_items(id) ON DELETE SET NULL,
    section_title text,
    section_text text NOT NULL,
    section_order integer NOT NULL,
    page_start integer,
    page_end integer,
    token_count integer,
    embedding halfvec(384),
    text_search tsvector GENERATED ALWAYS AS (
        to_tsvector('english', coalesce(section_title, '') || ' ' || coalesce(section_text, ''))
    ) STORED,
    municipality_id bigint REFERENCES municipalities(id) DEFAULT 1,
    created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indexes
CREATE INDEX idx_document_sections_document ON document_sections(document_id);
CREATE INDEX idx_document_sections_agenda_item ON document_sections(agenda_item_id);
CREATE INDEX idx_document_sections_search ON document_sections USING gin(text_search);
CREATE INDEX idx_document_sections_embedding ON document_sections
    USING hnsw (embedding halfvec_cosine_ops);

-- RLS
ALTER TABLE document_sections ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON document_sections FOR SELECT USING (true);

-- Match function for vector similarity search
CREATE OR REPLACE FUNCTION match_document_sections (
  query_embedding halfvec(384),
  match_threshold float,
  match_count int,
  filter_municipality_id bigint DEFAULT NULL
)
RETURNS TABLE (
  id bigint,
  document_id bigint,
  agenda_item_id bigint,
  section_title text,
  section_text text,
  section_order int,
  similarity float
)
LANGUAGE plpgsql
SET search_path = 'public'
AS $$
BEGIN
  RETURN QUERY
  SELECT
    ds.id,
    ds.document_id,
    ds.agenda_item_id,
    ds.section_title,
    ds.section_text,
    ds.section_order,
    1 - (ds.embedding <=> query_embedding) AS similarity
  FROM document_sections ds
  WHERE (filter_municipality_id IS NULL OR ds.municipality_id = filter_municipality_id)
    AND 1 - (ds.embedding <=> query_embedding) > match_threshold
  ORDER BY ds.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;
