-- View Royal Council Intelligence Platform - Consolidated Schema Bootstrap
-- Includes Core Relational Schema + Intelligence Layer (V2)

-- Enable pgvector for semantic search
CREATE EXTENSION IF NOT EXISTS vector;

-- 0. TYPES & ENUMS
DO $$ BEGIN
    CREATE TYPE meeting_type AS ENUM (
        'Regular Council',
        'Special Council',
        'Committee of the Whole',
        'Public Hearing',
        'Board of Variance',
        'Standing Committee',
        'Advisory Committee'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE org_classification AS ENUM (
        'Council',
        'Committee',
        'Board',
        'Advisory Committee',
        'Staff',
        'Other'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 0.1 TRIGGER FUNCTION
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 1. ORGANIZATIONS
CREATE TABLE organizations (
    id bigint generated by default as identity primary key,
    name text not null unique,
    classification org_classification default 'Committee',
    meta jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TRIGGER set_timestamp_organizations BEFORE UPDATE ON organizations FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- 2. PEOPLE
CREATE TABLE people (
    id bigint generated by default as identity primary key,
    name text not null unique,
    is_councillor boolean default false,
    email text,
    image_url text,
    bio text,
    voice_fingerprint_id text,
    meta jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TRIGGER set_timestamp_people BEFORE UPDATE ON people FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- 3. MEMBERSHIPS
CREATE TABLE memberships (
    id bigint generated by default as identity primary key,
    person_id bigint REFERENCES people(id) ON DELETE CASCADE not null,
    organization_id bigint REFERENCES organizations(id) ON DELETE CASCADE not null,
    role text, -- "Chair", "Vice-Chair", "Member"
    start_date date,
    end_date date,
    meta jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TRIGGER set_timestamp_memberships BEFORE UPDATE ON memberships FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- 4. ELECTIONS: Governance History
CREATE TABLE elections (
    id bigint generated by default as identity primary key,
    name text not null unique, -- "2022 General Local Election"
    election_date date not null,
    classification text, -- "General", "By-election"
    term_length_years int,
    notes text,
    source_id int, -- CivicInfo ID
    meta jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TRIGGER set_timestamp_elections BEFORE UPDATE ON elections FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

CREATE TABLE election_offices (
    id bigint generated by default as identity primary key,
    election_id bigint REFERENCES elections(id) ON DELETE CASCADE not null,
    office text not null, -- "Mayor", "Councillor"
    seats_available int,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(election_id, office)
);

CREATE TRIGGER set_timestamp_election_offices BEFORE UPDATE ON election_offices FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

CREATE TABLE candidacies (
    id bigint generated by default as identity primary key,
    election_office_id bigint REFERENCES election_offices(id) ON DELETE CASCADE not null,
    person_id bigint REFERENCES people(id) ON DELETE CASCADE not null,
    is_elected boolean default false,
    is_acclaimed boolean default false,
    votes_received int,
    meta jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(election_office_id, person_id)
);

CREATE TRIGGER set_timestamp_candidacies BEFORE UPDATE ON candidacies FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- 5. MEETINGS
CREATE TABLE meetings (
    id bigint generated by default as identity primary key,
    organization_id bigint REFERENCES organizations(id) ON DELETE SET NULL,
    title text not null,
    meeting_date date not null,
    type meeting_type,
    status text default 'Planned', -- 'Planned', 'Completed', 'Cancelled'

    -- Ingestion Status Flags
    has_agenda boolean default false,
    has_minutes boolean default false,
    has_transcript boolean default false,

    video_url text,
    minutes_url text,
    agenda_url text,
    video_duration_seconds int,
    chair_person_id bigint REFERENCES people(id) ON DELETE SET NULL,
    archive_path text unique,
    summary text,
    embedding vector(768),
    meta jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TRIGGER set_timestamp_meetings BEFORE UPDATE ON meetings FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- 6. ATTENDANCE
CREATE TABLE attendance (
    id bigint generated by default as identity primary key,
    meeting_id bigint REFERENCES meetings(id) ON DELETE CASCADE not null,
    person_id bigint REFERENCES people(id) ON DELETE CASCADE not null,
    attendance_mode text check (attendance_mode in ('In Person', 'Remote', 'Absent', 'Regrets', 'Unknown')) default 'Unknown',
    arrival_time timestamp with time zone,
    departure_time timestamp with time zone,
    notes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(meeting_id, person_id)
);

CREATE TRIGGER set_timestamp_attendance BEFORE UPDATE ON attendance FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- 7. MATTERS (Longitudinal topics/bylaws)
CREATE TABLE matters (
    id bigint generated by default as identity primary key,
    title text not null,
    identifier text unique, -- "Bylaw 1540"
    description text,
    plain_english_summary text,
    category text,
    status text default 'Active',
    first_seen date,
    last_seen date,
    embedding vector(768),
    meta jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TRIGGER set_timestamp_matters BEFORE UPDATE ON matters FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- 8. AGENDA ITEMS
CREATE TABLE agenda_items (
    id bigint generated by default as identity primary key,
    meeting_id bigint REFERENCES meetings(id) ON DELETE CASCADE not null,
    matter_id bigint REFERENCES matters(id) ON DELETE SET NULL,
    parent_id bigint REFERENCES agenda_items(id) ON DELETE CASCADE,

    item_order text,
    title text not null,
    description text,
    plain_english_summary text,
    category text,

    is_consent_agenda boolean default false,
    matter_status_snapshot text,
    related_address text,
    neighborhood text,
    debate_summary text,
    is_controversial boolean default false,

    discussion_start_time float,
    discussion_end_time float,
    financial_cost numeric,
    funding_source text,
    keywords text[],

    source_file text,
    embedding vector(768),
    meta jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TRIGGER set_timestamp_agenda_items BEFORE UPDATE ON agenda_items FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

CREATE INDEX IF NOT EXISTS idx_agenda_neighborhood ON agenda_items(neighborhood);

-- 9. TOPICS (Controlled taxonomy)
CREATE TABLE topics (
    id bigint generated by default as identity primary key,
    name text not null unique,
    description text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TRIGGER set_timestamp_topics BEFORE UPDATE ON topics FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

CREATE TABLE agenda_item_topics (
    agenda_item_id bigint REFERENCES agenda_items(id) ON DELETE CASCADE,
    topic_id bigint REFERENCES topics(id) ON DELETE CASCADE,
    PRIMARY KEY (agenda_item_id, topic_id)
);

-- 10. MOTIONS
CREATE TABLE motions (
    id bigint generated by default as identity primary key,
    meeting_id bigint REFERENCES meetings(id) ON DELETE CASCADE not null,
    agenda_item_id bigint REFERENCES agenda_items(id) ON DELETE CASCADE not null,

    mover text,
    seconder text,
    mover_id bigint REFERENCES people(id) ON DELETE SET NULL,
    seconder_id bigint REFERENCES people(id) ON DELETE SET NULL,
    text_content text not null,
    plain_english_summary text,

    disposition text, -- "Substantive", "Procedural", "Tabled", "Referred"
    result text, -- "CARRIED", "DEFEATED", "WITHDRAWN"

    yes_votes int DEFAULT 0,
    no_votes int DEFAULT 0,
    abstain_votes int DEFAULT 0,
    absent_votes int DEFAULT 0,

    time_offset_seconds float,
    financial_cost numeric,
    funding_source text,

    embedding vector(768),
    meta jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TRIGGER set_timestamp_motions BEFORE UPDATE ON motions FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- 11. VOTES
CREATE TABLE votes (
    id bigint generated by default as identity primary key,
    motion_id bigint REFERENCES motions(id) ON DELETE CASCADE not null,
    person_id bigint REFERENCES people(id) ON DELETE CASCADE not null,
    vote text not null, -- "Yes", "No", "Abstain", "Recused"
    recusal_reason text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(motion_id, person_id)
);

CREATE TRIGGER set_timestamp_votes BEFORE UPDATE ON votes FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- 12. TRANSCRIPT SEGMENTS
CREATE TABLE transcript_segments (
    id bigint generated by default as identity primary key,
    meeting_id bigint REFERENCES meetings(id) ON DELETE CASCADE not null,
    person_id bigint REFERENCES people(id) ON DELETE SET NULL,
    agenda_item_id bigint REFERENCES agenda_items(id) ON DELETE SET NULL,
    motion_id bigint REFERENCES motions(id) ON DELETE SET NULL,

    speaker_name text,
    speaker_role text,

    start_time float not null,
    end_time float not null,
    text_content text not null,
    corrected_text_content text,

    attribution_source text default 'AI_DIARIZATION',
    is_verified boolean default false,
    is_procedural boolean default false,
    sentiment_score float,
    embedding vector(768),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TRIGGER set_timestamp_transcript_segments BEFORE UPDATE ON transcript_segments FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- 13. SPEAKER ALIASES
CREATE TABLE meeting_speaker_aliases (
    id bigint generated by default as identity primary key,
    meeting_id bigint REFERENCES meetings(id) ON DELETE CASCADE not null,
    speaker_label text not null,
    person_id bigint REFERENCES people(id) ON DELETE CASCADE not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(meeting_id, speaker_label)
);

CREATE TRIGGER set_timestamp_meeting_speaker_aliases BEFORE UPDATE ON meeting_speaker_aliases FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- 14. MEETING EVENTS
CREATE TABLE meeting_events (
    id bigint generated by default as identity primary key,
    meeting_id bigint REFERENCES meetings(id) ON DELETE CASCADE not null,
    person_id bigint REFERENCES people(id) ON DELETE CASCADE not null,
    event_type text not null, -- 'Left Meeting', 'Returned', 'Recused'
    time_offset_seconds int,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TRIGGER set_timestamp_meeting_events BEFORE UPDATE ON meeting_events FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- 15. BYLAWS (Reference Documents)
CREATE TABLE bylaws (
    id bigint generated by default as identity primary key,
    title text not null,
    bylaw_number text,
    year int,
    category text,
    status text default 'Active',
    file_path text unique,
    source_url text,
    full_text text,
    plain_english_summary text,
    embedding vector(768),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TRIGGER set_timestamp_bylaws BEFORE UPDATE ON bylaws FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

CREATE TABLE bylaw_chunks (
    id bigint generated by default as identity primary key,
    bylaw_id bigint REFERENCES bylaws(id) ON DELETE CASCADE not null,
    chunk_index int not null,
    text_content text not null,
    embedding vector(768),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE INDEX IF NOT EXISTS idx_bylaws_title ON bylaws(title);
CREATE INDEX IF NOT EXISTS idx_bylaws_number ON bylaws(bylaw_number);
CREATE INDEX IF NOT EXISTS idx_bylaw_chunks_bylaw_id ON bylaw_chunks(bylaw_id);

-- 17. SEMANTIC SEARCH INDEXES (HNSW)
-- We use cosine distance for Gemini embeddings.
CREATE INDEX IF NOT EXISTS idx_transcript_segments_embedding ON transcript_segments USING hnsw (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_motions_embedding ON motions USING hnsw (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_agenda_items_embedding ON agenda_items USING hnsw (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_matters_embedding ON matters USING hnsw (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_meetings_embedding ON meetings USING hnsw (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_bylaws_embedding ON bylaws USING hnsw (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_bylaw_chunks_embedding ON bylaw_chunks USING hnsw (embedding vector_cosine_ops);

-- 18. ROW LEVEL SECURITY
ALTER TABLE organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE people ENABLE ROW LEVEL SECURITY;
ALTER TABLE memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE elections ENABLE ROW LEVEL SECURITY;
ALTER TABLE election_offices ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidacies ENABLE ROW LEVEL SECURITY;
ALTER TABLE meetings ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE matters ENABLE ROW LEVEL SECURITY;
ALTER TABLE agenda_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE agenda_item_topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE motions ENABLE ROW LEVEL SECURITY;
ALTER TABLE votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE transcript_segments ENABLE ROW LEVEL SECURITY;
ALTER TABLE meeting_speaker_aliases ENABLE ROW LEVEL SECURITY;
ALTER TABLE meeting_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE bylaws ENABLE ROW LEVEL SECURITY;
ALTER TABLE bylaw_chunks ENABLE ROW LEVEL SECURITY;

-- 19. PUBLIC READ POLICIES
CREATE POLICY "Allow public read-only access on organizations" ON organizations FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on people" ON people FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on memberships" ON memberships FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on elections" ON elections FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on election_offices" ON election_offices FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on candidacies" ON candidacies FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on meetings" ON meetings FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on attendance" ON attendance FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on matters" ON matters FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on agenda_items" ON agenda_items FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on topics" ON topics FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on agenda_item_topics" ON agenda_item_topics FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on motions" ON motions FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on votes" ON votes FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on transcript_segments" ON transcript_segments FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on meeting_speaker_aliases" ON meeting_speaker_aliases FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on meeting_events" ON meeting_events FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on bylaws" ON bylaws FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on bylaw_chunks" ON bylaw_chunks FOR SELECT TO public USING (true);

CREATE POLICY "Enable write access for service role on bylaws" ON bylaws USING (auth.role() = 'service_role');
CREATE POLICY "Enable write access for service role on bylaw_chunks" ON bylaw_chunks USING (auth.role() = 'service_role');

-- 20. SEMANTIC SEARCH FUNCTIONS (RPC)

CREATE OR REPLACE FUNCTION match_bylaws (
  query_embedding vector(768),
  match_threshold float,
  match_count int
)
RETURNS TABLE (
  id bigint,
  title text,
  bylaw_number text,
  plain_english_summary text,
  similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    b.id,
    b.title,
    b.bylaw_number,
    b.plain_english_summary,
    1 - (b.embedding <=> query_embedding) AS similarity
  FROM bylaws b
  WHERE 1 - (b.embedding <=> query_embedding) > match_threshold
  ORDER BY b.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

CREATE OR REPLACE FUNCTION match_bylaw_chunks (
  query_embedding vector(768),
  match_threshold float,
  match_count int,
  filter_bylaw_id bigint DEFAULT NULL
)
RETURNS TABLE (
  id bigint,
  bylaw_id bigint,
  chunk_index int,
  text_content text,
  similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    bc.id,
    bc.bylaw_id,
    bc.chunk_index,
    bc.text_content,
    1 - (bc.embedding <=> query_embedding) AS similarity
  FROM bylaw_chunks bc
  WHERE (filter_bylaw_id IS NULL OR bc.bylaw_id = filter_bylaw_id)
    AND 1 - (bc.embedding <=> query_embedding) > match_threshold
  ORDER BY bc.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

COMMENT ON FUNCTION match_bylaws IS 'Semantic similarity search for bylaws.';
COMMENT ON FUNCTION match_bylaw_chunks IS 'Semantic similarity search for bylaw segments.';
